apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  # property-like keys; each key maps to a simple value
  credentials: |
    [bucket]
    aws_access_key=AKIAZ2RM5WT3WNZWL3VM
    aws_secret_access_key=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
    [default]
    aws_access_key=AKIA5U7C5R6ENLIJRZPH
    aws_secret_access_key=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