apiVersion: v1
kind: ConfigMap
metadata:
  name: udagram-aws
data:
  # property-like keys; each key maps to a simple value
  credentials: |
   [default]
    aws_access_key_id = AKIA5U7C5R6EE4A32L7Z
    aws_secret_access_key = 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