version: "3.9"

services:
  backend-user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user
    ports:
      - "9001:8080"
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  backend-feed:
    build: 
      context: ./udagram-api-feed
    image: udagram-api-feed
    ports:
      - "9002:8080"
    environment:
      POSTGRES_USERNAME: $POSTGRES_USERNAME
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD 
      POSTGRES_DB: $POSTGRES_DB 
      POSTGRES_HOST: $POSTGRES_HOST
      AWS_REGION: $AWS_REGION 
      AWS_PROFILE: $AWS_PROFILE 
      AWS_BUCKET: $AWS_BUCKET
      JWT_SECRET: $JWT_SECRET
      URL: "http://localhost:8100"

  frontend:
    build: 
      context: ./udagram-frontend
    image: udagram-frontend:local
    ports:
      - "9003:8100"

  udagram-reverseproxy:
    build: 
      context: ./udagram-reverseproxy
    image: reverseproxy
    ports:
      - "8050:8080"