# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      Greeting: Hi
    steps:
    - uses: actions/checkout@v3
    - run: echo "first action tuts $Greeting"
    - run: ls -l
    - run: docker-compose -f docker-compose.yml build --parallel
    - run: docker tag udagram-api-feed nstandev/udagram-api-feed:v1
    - run: docker tag udagram-api-user nstandev/udagram-api-user:v1
    - run: docker tag udagram-frontend:local nstandev/udagram-frontend:v1 
    - run: docker tag reverseproxy nstandev/reverseproxy:v1
    - run: docker push nstandev/udagram-api-feed:v1
    - run: docker push nstandev/udagram-api-user:v1
    - run: docker push nstandev/udagram-frontend:v1
    - run: docker push nstandev/reverseproxy:v1 